defaults:
  - _self_

hydra:
  job:
    chdir: false 
    
experiment:
  name: "butterfly_eval_initial_project_setup_full_nymphalidae_dataset"
  seed: 42
  device: "cuda"

mode: "eval"

model:
  _target_: "models.bioclip.BioCLIPModel"
  device: "cuda"
  model_name: "hf-hub:imageomics/bioclip"

# Comment other model and uncomment this one to use OpenAI CLIP
# model:
#   _target_: "models.openai_clip.OpenAICLIPModel" 
#   device: "cuda"
#   model_name: "openai/clip-vit-base-patch32"


# data:
#   _target_: "dataloaders.vlmbio_loader.VLMBioDataLoader"
#   base_dir: "data/VLM4Bio/datasets"
#   group: "Fish"
#   metadata_file: "metadata_10k.csv"
#   batch_size: 128

data:
  _target_: "dataloaders.butterfly_dataset_loader.ButterflyDatasetDataLoader"
  base_dir: "C:\\Mani\\learn\\Courses\\BioCosmos\\Butterfly_Project\\Data"
  metadata_dir: "C:\\Mani\\learn\\Courses\\BioCosmos\\Butterfly_Project\\Data\\nymphalidae_whole_specimen-v240606\\metadata"
  # base_dir: "/blue/arthur.porto-biocosmos/data/datasets"
  # metadata_dir: "/blue/arthur.porto-biocosmos/data/datasets/nymphalidae_whole_specimen-v240606/metadata"
  group: "nymphalidae_whole_specimen-v240606"
  metadata_file: "data_meta-nymphalidae_whole_specimen-v240606_subset.csv"
  batch_size: 128

#Can add multiple evaluators
evaluators:
  - _target_: "evaluation.zero_shot_evaluator.ZeroShotEvaluator"
    n_samples: 2000
    metrics: ["accuracy"]
    show_progress: true
    
