defaults:
  - _self_

hydra:
  job:
    chdir: false 
    
experiment:
  name: "butterfly_eval_initial_project_setup_full_nymphalidae_dataset"
  seed: 42
  device: "cuda"

mode: "eval"

model:
  _target_: "models.bioclip.BioCLIPModel"
  device: "cuda"
  model_name: "hf-hub:imageomics/bioclip"

# Comment other model and uncomment this one to use OpenAI CLIP
# model:
#   _target_: "models.openai_clip.OpenAICLIPModel"
#   device: "cuda"
#   model_name: "openai/clip-vit-base-patch32"


# data:
#   _target_: "dataloaders.vlmbio_loader.VLMBioDataLoader"
#   base_dir: "data/VLM4Bio/datasets"
#   group: "Fish"
#   metadata_file: "metadata_10k.csv"
#   batch_size: 128

data:
  _target_: "dataloaders.butterfly_dataset_loader.ButterflyDatasetDataLoader"
  base_dir: "C:\\Mani\\learn\\Courses\\BioCosmos\\Butterfly_Project\\Data"
  metadata_dir: "C:\\Mani\\learn\\Courses\\BioCosmos\\Butterfly_Project\\Data\\nymphalidae_whole_specimen-v240606\\metadata"
  # base_dir: "/blue/arthur.porto-biocosmos/data/datasets"
  # metadata_dir: "/blue/arthur.porto-biocosmos/data/datasets/nymphalidae_whole_specimen-v240606/metadata"
  group: "nymphalidae_whole_specimen-v240606"
  metadata_file: "data_meta-nymphalidae_whole_specimen-v240606_subset.csv"
  batch_size: 128

# Evaluation metrics from main_trial.py integrated as pluggable evaluators
evaluators:
  # Binary relevance metrics (species-level matches only)
  - _target_: "evaluation.precision_at_k_evaluator.PrecisionAtKEvaluator"
    n_samples: 500
    k_values: [1, 5, 50]
    show_progress: true
    
  - _target_: "evaluation.recall_at_k_evaluator.RecallAtKEvaluator"
    n_samples: 500
    k_values: [1, 5, 50]
    show_progress: true
    
  - _target_: "evaluation.map_evaluator.mAPEvaluator"
    n_samples: 500
    show_progress: true
    
  # Hierarchical relevance metrics (multi-level taxonomy with exponential gain)
  - _target_: "evaluation.ndcg_evaluator.NDCGEvaluator"
    n_samples: 500
    k_values: [1, 5, 50]
    primary_k: 50
    show_progress: true
